USE [master]
GO

/****** Object:  Database [MACT]    Script Date: 9/13/2022 8:55:38 PM ******/
CREATE DATABASE [MACT]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'MACT', FILENAME = N'/var/opt/mssql/data/MACT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'MACT_log', FILENAME = N'/var/opt/mssql/data/MACT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MACT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MACT] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [MACT] SET ANSI_NULLS OFF
GO

ALTER DATABASE [MACT] SET ANSI_PADDING OFF
GO

ALTER DATABASE [MACT] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [MACT] SET ARITHABORT OFF
GO

ALTER DATABASE [MACT] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [MACT] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [MACT] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [MACT] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [MACT] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [MACT] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [MACT] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [MACT] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [MACT] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [MACT] SET  DISABLE_BROKER
GO

ALTER DATABASE [MACT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [MACT] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [MACT] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [MACT] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [MACT] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [MACT] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [MACT] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [MACT] SET RECOVERY FULL
GO

ALTER DATABASE [MACT] SET  MULTI_USER
GO

ALTER DATABASE [MACT] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [MACT] SET DB_CHAINING OFF
GO

ALTER DATABASE [MACT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [MACT] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [MACT] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [MACT] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

ALTER DATABASE [MACT] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MACT] SET  READ_WRITE
GO


